# top level stuff you probably don't need to touch




# edit here to achieve your personal greatness
url: http://saif.mektekbd.com
baseurl: http://saif.mektekbd.com/
title: Saif Maruf
author: Saif Maruf
description: Personal blog and resume
avatar: saif.jpg
email: saif.mektek@gmail.com
phone: +8801913344679
facebook: saif.maruf
github: Saif-Uz-Zaman # username
twitter: Saif_MekTek
linkedin: saif-maruf-7a5b0913b
stackoverflow: users/8098885/saif-maruf   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
disqus: MekTek
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
